//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeYoutubeModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeopleBicycle
    {
        public int Id { get; set; }
        public Nullable<int> PeopleId { get; set; }
        public string Bicycle { get; set; }
        public Nullable<System.DateTime> BuyDate { get; set; }
    }
}
